
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/spree_ecomerce_development
test:
  <<: *default
  database: db/spree_ecomerce_test

production:
  <<: *default
  database: db/spree_ecomerce_production
